# SPDX-License-Identifier: MIT
---

- name: Ensure metric log location is configured
  lineinfile:
    path: "{{ __pcp_conf }}"
    regexp: '^PCP_ARCHIVE_DIR='
    line: PCP_ARCHIVE_DIR={{ pcp_archive_dir }}
  notify:
    - restart pmlogger
    - restart pmproxy

- name: Ensure performance metric logging is configured
  template:
    src: pmlogger.defaults.j2
    dest: "{{ __pcp_pmlogger_defaults_path }}"
    mode: 0644
  notify: restart pmlogger

- name: Ensure performance metric logging retention period is set
  template:
    src: pmlogger.timers.j2
    dest: "{{ __pcp_pmlogger_timers_path }}"
    mode: 0644
  notify: restart pmlogger

- name: Enable performance metric logging for targeted hosts (with control.d)
  template:
    src: pmlogger.controld.j2
    dest: "{{ __pcp_pmlogger_control_d_path }}/{{ item }}"
    mode: 0644
  loop: "{{ pcp_target_hosts|default([]) }}"
  notify: restart pmlogger
  when:
    - not pcp_single_control|d(false)|bool
    - pcp_target_hosts|d([])

- name: Enable performance metric logging for targeted hosts (single control)
  template:
    src: pmlogger.control.j2
    dest: "{{ __pcp_pmlogger_control_path }}"
    mode: 0644
  notify: restart pmlogger
  when:
    - pcp_single_control|d(true)|bool
    - pcp_target_hosts|d([])

- name: Ensure performance metric logging is running and enabled on boot
  service:
    name: pmlogger
    state: started
    enabled: yes
