apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controller
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: true
  ingress_type: Route
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  task_privileged: false
  projects_storage_access_mode: ReadWriteOnce
  projects_persistence: true
  replicas: 1
  admin_user: admin
  projects_use_existing_claim: _Yes_
  projects_existing_claim: aac-data
  init_container_image: registry.access.redhat.com/ubi8/ubi
  init_container_image_version: latest
  init_container_extra_commands: |
    until getent hosts controller-postgres-13
    do echo waiting for controller-postgres-13
    sleep 2
    done
