kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aac-data
  namespace: ansible-automation-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
